### ISSUE TITLE
About the released Processed Data

### ISSUE THREAD

**Issue by BigHandsome-Lin** [thuiar/MMSA#48]
Thank you for your wonderful work! 
But I have some questions about the released dataset in [BaiduYun Disk](https://pan.baidu.com/s/1F2CgPCeG4eI6nmrRwp4ESA?pwd=7ppk):  The Processed Data in MOSEI have 74 and 35 feature dimensions for audio and vision modality, which can be figured out that these two modalities features are extracted by COVAREP and Facet. However, the Processed Data in MOSI have 5 and 20 feature dimensions for audio and vision modality, what feature extractor did you use to extract MOSI data? As far as I know, MOSI audio and vision modality features extrated by COVAREP and Facet have 74 and 47 feature dimensions. 
Thank you for your answer!

**Comment by Columbine21** [comment]
Hi @GHBigHandsome, the provided audio and visual modality features are the original ones extracted by the CMU Multi-camp team (http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/). 

As stated in our ACL22 Demo paper (intro section), the feature **can not** be reproduced easily due to the manually feature selection (as stated in http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosi/readme.MD).
