### ISSUE TITLE
Issues for pytorch_transformers

### ISSUE THREAD

**Issue by bingxindu** [thuiar/MMSA#9]
I installed the same version of pytorch_transformers(eg: pytorch_transformers==1.0.0 in requirements.txt file), however i got "ModuleNotFoundError: No module named 'pytorch_transformers.amir_tokenization'" error in "/models/singleTask/BERT_MAG.py" file. So, someone else can tell me why?

**Comment by iyuge2** [comment]
Hi, the original pytorch_transformer is installed from source code according to the instruction in raw codes of MAG, not compatible with official version. Recently, the author of MAG uploaded a new code version at [BERT_multimodal_transformer](https://github.com/WasifurRahman/BERT_multimodal_transformer). Due to the time limitation, we haven't updatad the support for BERT_MAG. If you want to use that, you can 
refer codes in [BERT_multimodal_transformer](https://github.com/WasifurRahman/BERT_multimodal_transformer). Or you can remove BERT_MAG from our repo codes.

**Comment by bingxindu** [comment]
thanks, i got it!

> Hi, the original pytorch_transformer is installed from source code according to the instruction in raw codes of MAG, not compatible with official version. Recently, the author of MAG uploaded a new code version at [BERT_multimodal_transformer](https://github.com/WasifurRahman/BERT_multimodal_transformer). Due to the time limitation, we haven't updatad the support for BERT_MAG. If you want to use that, you can
> refer codes in [BERT_multimodal_transformer](https://github.com/WasifurRahman/BERT_multimodal_transformer). Or you can remove BERT_MAG from our repo codes.

**Comment by bingxindu** [comment]
> Hi, the original pytorch_transformer is installed from source code according to the instruction in raw codes of MAG, not compatible with official version. Recently, the author of MAG uploaded a new code version at [BERT_multimodal_transformer](https://github.com/WasifurRahman/BERT_multimodal_transformer). Due to the time limitation, we haven't updatad the support for BERT_MAG. If you want to use that, you can
> refer codes in [BERT_multimodal_transformer](https://github.com/WasifurRahman/BERT_multimodal_transformer). Or you can remove BERT_MAG from our repo codes.

thanks, i got it!
